// PT-BR long-form persuasion content for /tratamentos/[slug] pages.
// 12 treatments x 7 sections each. Single source of truth.
// Voice: patient as protagonist; clinic supports transformation; "sem pressa" mechanism implicit.

export type TreatmentFaqItem = { question: string; answer: string };

export type TreatmentContent = {
  metadata: { title: string; description: string };
  hero: { eyebrow: string; bronze: string; bronzeItalic: string; description: string };
  consider: {
    eyebrow: string; title: string; titleItalic: string;
    intro: string; signals: string[]; bridge: string;
  };
  approach: {
    eyebrow: string; title: string; titleItalic: string;
    intro: string; steps: { number: string; title: string; body: string }[];
  };
  results: {
    eyebrow: string; title: string; titleItalic: string;
    paragraphs: string[];
    moments: { title: string; body: string }[];
  };
  investment: {
    eyebrow: string; title: string; titleItalic: string;
    paragraphs: string[]; factors: string[]; closing: string;
  };
  faq: TreatmentFaqItem[];
  closing: { eyebrow: string; bronze: string; bronzeItalic: string; description: string };
};

export const TREATMENTS_CONTENT: Record<string, TreatmentContent> = {
  'implantes-dentarios': {
    metadata: { title: 'Implantes dentários | Biodonth', description: 'Implantes dentários em Artur Alvim, São Paulo. Reabilitação de dentes perdidos com planejamento integrado e acompanhamento de longo prazo.' },
    hero: { eyebrow: 'Tratamento \u2022 Implantes', bronze: 'O dente que voltou', bronzeItalic: 'a ser seu.', description: 'Implante dentário não é prótese — é raiz nova. O dente que substitui o que faltava se comporta como o dente que sempre esteve ali: morde, fala, dura.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'o implante é o caminho.', intro: 'Implantes substituem dentes extraídos, perdidos por trauma, ou comprometidos. Vale conversar quando:', signals: ['Você evita morder com um dos lados porque há um espaço vazio.', 'Você usa prótese removível há anos e gostaria de não tirar mais nada da boca para limpar.', 'Um dente foi extraído e os vizinhos começaram a inclinar para o espaço vazio.', 'Você passou a falar diferente depois de perder um dente.', 'Tem uma ponte antiga que precisa ser refeita sem desgastar os dentes vizinhos.'], bridge: 'Nenhum desses sinais decide o tratamento sozinho. O que decide é a avaliação completa, feita na primeira consulta, com tempo de sobra.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'O implante na Biodonth,', titleItalic: 'passo a passo.', intro: 'Cada etapa é planejada antes da próxima começar — e nada é apressado.', steps: [{ number: '01', title: 'Avaliação inicial completa.', body: 'Conversamos sobre seu histórico, hábitos, expectativas. Exame clínico completo e indicação de exames de imagem.' }, { number: '02', title: 'Planejamento integrado.', body: 'Implantodontista, periodontista e protesista discutem o caso juntos antes de qualquer proposta.' }, { number: '03', title: 'Apresentação do plano.', body: 'Você recebe o plano escrito — etapas, prazos, valores, alternativas. Leva para casa, pensa com calma.' }, { number: '04', title: 'Preparo (se necessário).', body: 'Tratamento de gengiva, enxerto ósseo quando o osso é insuficiente, ou extrações de dentes comprometidos.' }, { number: '05', title: 'Cirurgia do implante.', body: 'Cirurgia ambulatorial sob anestesia local. 30 a 90 minutos por implante. Maioria volta às atividades no dia seguinte.' }, { number: '06', title: 'Osseointegração.', body: 'O implante se funde ao osso em 3 a 6 meses. Você usa prótese provisória nesse período.' }, { number: '07', title: 'Coroa final.', body: 'Moldes, escolha de cor, instalação da coroa definitiva. A partir daí, você morde e sorri normalmente.' }, { number: '08', title: 'Manutenção de longo prazo.', body: 'Consultas a cada 6 meses. Pacientes que fazem manutenção mantêm implantes por décadas.' }] },
    results: { eyebrow: 'O que esperar do resultado', title: 'O que muda na vida', titleItalic: 'depois do implante.', paragraphs: ['O resultado de um implante bem feito não é estético — é existencial. A boca volta a ter a função que tinha.', 'Você morde dos dois lados sem pensar. Fala sem perceber. Sorri sem cobrir.'], moments: [{ title: 'A maçã, a carne, o pão.', body: 'Comer volta a ser sobre o sabor, não sobre qual lado consegue mastigar.' }, { title: 'A foto da família.', body: 'Você sorri inteiro. Sem pensar onde o sorriso encontra a falta.' }, { title: 'A conversa sem cálculo.', body: 'Sem palavras evitadas, sem distância calculada da outra pessoa.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Quanto custa,', titleItalic: 'quanto tempo demora.', paragraphs: ['O investimento varia conforme a complexidade. Não trabalhamos com preços padronizados porque cada caso é diferente.', 'Na primeira consulta, você recebe o plano com valores discriminados e opções de parcelamento em até 12 vezes.'], factors: ['Quantidade de implantes necessários.', 'Necessidade de enxerto ósseo.', 'Tipo de coroa final.', 'Marca e linha do implante.', 'Tempo total do tratamento (4 a 9 meses em geral).'], closing: 'Não pressionamos decisões na primeira consulta. Você leva o plano e volta quando estiver pronto.' },
    faq: [{ question: 'Implante dói?', answer: 'A cirurgia é feita sob anestesia local. No pós, desconforto leve a moderado nas primeiras 48h, controlado com analgésicos comuns.' }, { question: 'Quanto tempo do início ao fim?', answer: 'Casos simples: 4 a 6 meses. Com enxerto: 9 a 12 meses. A osseointegração é a etapa mais longa.' }, { question: 'Implante dura para sempre?', answer: 'Literatura mostra taxa de sucesso superior a 95% em 10 anos. Muitos casos passam de 25-30 anos com manutenção adequada.' }, { question: 'Posso fazer com pouco osso?', answer: 'Em muitos casos, sim — com enxerto ósseo prévio. A tomografia na avaliação mostra exatamente o cenário.' }, { question: 'Fico sem dente durante o tratamento?', answer: 'Em geral, não. Usamos prótese provisória estética durante a osseointegração.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'O caminho começa', bronzeItalic: 'com uma conversa.', description: 'Implante é decisão grande. Por isso a primeira consulta tem tempo de sobra. Para que você saia entendendo o que precisa, com um plano na mão.' },
  },

  'ortodontia': {
    metadata: { title: 'Ortodontia | Biodonth', description: 'Tratamento ortodôntico em Artur Alvim — aparelho fixo discreto ou alinhadores transparentes, com planejamento integrado.' },
    hero: { eyebrow: 'Tratamento \u2022 Ortodontia', bronze: 'Dentes no lugar.', bronzeItalic: 'Sem virar identidade.', description: 'Aparelho não precisa entrar antes de você na sala. Hoje há mais de uma forma de alinhar dentes.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'a ortodontia faz diferença.', intro: 'Ortodontia não é só estética — é saúde bucal, função e autoestima. Vale conversar quando:', signals: ['Dentes apinhados que dificultam escovação e fio dental.', 'Mordida que "trava" — os dentes não se encaixam corretamente.', 'Espaço entre os dentes que incomoda ou cresceu com o tempo.', 'Mordida cruzada, aberta ou profunda.', 'Dor nas articulações da mandíbula, dores de cabeça ou ranger noturno.'], bridge: 'A primeira consulta inclui análise completa do sorriso, mordida e relação dos maxilares.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Dois caminhos,', titleItalic: 'a mesma destinação.', intro: 'Aparelho fixo ou alinhadores transparentes — a melhor via depende do seu caso, estilo de vida e cronograma.', steps: [{ number: '01', title: 'Avaliação inicial.', body: 'Análise dos dentes, mordida e articulações. Fotos, radiografias e escaneamento digital quando indicado.' }, { number: '02', title: 'Apresentação das opções.', body: 'Plano com as vias viáveis — aparelho metálico, estético ou alinhadores — com prazos e valores.' }, { number: '03', title: 'Instalação ou início dos alinhadores.', body: 'Aparelho fixo: 60-90 minutos, indolor. Alinhadores: primeira sequência com instruções de uso.' }, { number: '04', title: 'Acompanhamento.', body: 'Fixo: consultas mensais. Alinhadores: a cada 6-10 semanas. Fotos comparativas mostram evolução.' }, { number: '05', title: 'Finalização e contenção.', body: 'Remoção do aparelho e instalação de contenções para evitar recidiva.' }] },
    results: { eyebrow: 'O que esperar', title: 'Mais do que', titleItalic: 'dentes alinhados.', paragraphs: ['Resultado visível: sorriso simétrico e fotogênico. Resultado invisível: escovação mais eficaz, menos cáries, gengiva mais saudável.', 'Para a maioria dos adultos, há ainda a confiança recuperada de sorrir aberto e ser fotografado.'], moments: [{ title: 'O primeiro selfie de boca aberta.', body: 'Sem cálculo. Sem ângulo. Apenas o sorriso.' }, { title: 'A escovação que finalmente alcança.', body: 'Fio dental que desliza, cantos limpos, retorno ao dentista sem cárie nova.' }, { title: 'A mordida que para de te lembrar.', body: 'Sem trinco, sem tensão na ATM, sem dor de cabeça.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Tempo e custo,', titleItalic: 'sem rodeios.', paragraphs: ['Tempo: 12 a 36 meses, dependendo da complexidade. Casos leves: 6-9 meses.', 'Custo varia conforme o caminho. Parcelamento durante todo o tratamento — você paga conforme as consultas acontecem.'], factors: ['Tipo de aparelho ou alinhador.', 'Complexidade do caso.', 'Procedimentos auxiliares (extrações, mini-implantes).', 'Adesão do paciente (alinhadores: 20-22h/dia).', 'Idade (adultos demoram um pouco mais).'], closing: 'Na primeira consulta, você sai com ambos os caminhos apresentados lado a lado, quando viáveis.' },
    faq: [{ question: 'Adulto pode fazer aparelho?', answer: 'Sim. Mais de 35% dos pacientes ortodônticos no Brasil são adultos. Resultados igualmente previsíveis e duradouros.' }, { question: 'Alinhador serve para qualquer caso?', answer: 'Não. Funciona bem para apinhamento leve a moderado. Casos complexos se beneficiam mais do fixo.' }, { question: 'Atrapalha a fala?', answer: 'Nos primeiros 5-10 dias, adaptação leve. Depois, a fala se ajusta completamente.' }, { question: 'Vou precisar de contenção para sempre?', answer: 'Algum tipo de contenção é recomendado permanentemente. Os dentes têm tendência natural a se moverem.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'A consulta', bronzeItalic: 'começa o caminho.', description: 'Você sai da primeira consulta sabendo quais opções servem, quanto tempo cada uma leva, e quanto custa.' },
  },

  'alinhadores': {
    metadata: { title: 'Alinhadores transparentes | Biodonth', description: 'Alinhadores transparentes em Artur Alvim — correção ortodôntica discreta, removível e confortável.' },
    hero: { eyebrow: 'Tratamento \u2022 Alinhadores', bronze: 'Corrigir sem', bronzeItalic: 'que ninguém perceba.', description: 'Placas transparentes que movem os dentes de forma gradual. Você remove para comer, escovar e viver — e ninguém nota que está em tratamento.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'os alinhadores são para você.', intro: 'Alinhadores funcionam bem para casos leves a moderados. Vale conversar quando:', signals: ['Dentes levemente desalinhados ou apinhados.', 'Você quer tratamento ortodôntico discreto, sem aparelho visível.', 'Precisa de flexibilidade — remove para reuniões, fotos, eventos.', 'Já usou aparelho fixo e houve recidiva leve.', 'Quer corrigir espaçamentos ou pequenas rotações.'], bridge: 'Nem todo caso é indicado para alinhadores. A avaliação inicial define se esse caminho funciona para você.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'O tratamento invisível,', titleItalic: 'passo a passo.', intro: 'Planejamento digital do início ao fim — você vê a simulação do resultado antes de começar.', steps: [{ number: '01', title: 'Avaliação e escaneamento.', body: 'Análise clínica, fotos e escaneamento intraoral 3D. Sem moldagem convencional.' }, { number: '02', title: 'Simulação digital.', body: 'Você vê a movimentação planejada dos dentes, do início ao resultado final, antes de decidir.' }, { number: '03', title: 'Entrega da primeira sequência.', body: 'Instruções de uso: 20-22h por dia. Troca a cada 7-14 dias conforme o plano.' }, { number: '04', title: 'Acompanhamento.', body: 'Consultas a cada 6-10 semanas para monitorar e entregar novas placas.' }, { number: '05', title: 'Finalização e contenção.', body: 'Contenção fixa ou removível para manter o resultado alcançado.' }] },
    results: { eyebrow: 'O que esperar', title: 'Dentes alinhados,', titleItalic: 'rotina preservada.', paragraphs: ['O tratamento acontece enquanto sua vida continua normalmente. Sem metal, sem ajustes doloridos, sem restrições alimentares.', 'O resultado final é o mesmo da ortodontia convencional — para os casos indicados.'], moments: [{ title: 'A reunião sem aparelho.', body: 'Ninguém percebe. Você sorri, fala, apresenta — sem metal à vista.' }, { title: 'O jantar sem restrição.', body: 'Remove, come o que quiser, escova, recoloca. Simples.' }, { title: 'A foto do antes e depois.', body: 'A diferença que você acompanhou semana a semana, finalmente lado a lado.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Custo e prazo,', titleItalic: 'caso a caso.', paragraphs: ['Tempo: 6 a 18 meses para a maioria dos casos. Casos simples: 4-6 meses.', 'Investimento proporcional à complexidade. Parcelamento disponível.'], factors: ['Complexidade do caso.', 'Quantidade de placas necessárias.', 'Necessidade de attachments ou IPR.', 'Adesão ao uso diário (20-22h).'], closing: 'Na avaliação, você vê a simulação do resultado e recebe o plano com valores antes de decidir.' },
    faq: [{ question: 'Dói?', answer: 'Pressão leve nos primeiros 2-3 dias de cada placa nova. Desconforto menor que ajuste de aparelho fixo.' }, { question: 'Posso tirar para comer?', answer: 'Sim, essa é uma das vantagens. Remove para comer e escovar. Usa o restante do tempo.' }, { question: 'Funciona para qualquer caso?', answer: 'Não. Casos complexos com grandes movimentações se beneficiam mais do aparelho fixo. A avaliação define.' }, { question: 'E se eu esquecer de usar?', answer: 'Uso abaixo de 20h/dia compromete o resultado. O tratamento depende da sua disciplina diária.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'Veja o resultado', bronzeItalic: 'antes de começar.', description: 'A simulação digital mostra o caminho inteiro. Você decide depois de ver.' },
  },

  'facetas': {
    metadata: { title: 'Facetas e lentes de contato | Biodonth', description: 'Facetas e lentes de contato dentais em porcelana em Artur Alvim, planejadas no detalhe.' },
    hero: { eyebrow: 'Tratamento \u2022 Facetas', bronze: 'O sorriso que', bronzeItalic: 'ninguém percebe.', description: 'Faceta bem feita não é "trabalho de dentista". É o seu sorriso, naturalmente melhor.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'as facetas fazem sentido.', intro: 'Facetas corrigem cor, forma, tamanho ou pequenos desalinhamentos. Vale considerar quando:', signals: ['Cor que não responde a clareamento.', 'Forma dos dentes que incomoda — desgaste, bordas irregulares.', 'Diastemas discretos que você prefere fechar sem ortodontia.', 'Pequenas fraturas ou imperfeições que chamam atenção.', 'Você quer o passo final após ortodontia ou clareamento.'], bridge: 'Em muitos casos, clareamento ou ortodontia resolvem com menos desgaste. A primeira consulta serve para essa avaliação honesta.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'O caminho até', titleItalic: 'a faceta final.', intro: 'A diferença entre faceta natural e faceta "de novela" está no planejamento.', steps: [{ number: '01', title: 'Avaliação + referências.', body: 'Fotos, escaneamento, conversa sobre o que você gosta no seu sorriso e o que mudaria.' }, { number: '02', title: 'Mock-up + ensaio.', body: 'Simulação direta sobre seus dentes com resina temporária. Você vê e sente antes de qualquer coisa irreversível.' }, { number: '03', title: 'Preparo mínimo.', body: 'Menos de 0,5mm de esmalte. Em alguns casos, sem preparo nenhum. Você sai com provisórias estéticas.' }, { number: '04', title: 'Instalação definitiva.', body: 'Em ~90 minutos: teste, ajuste de cor, cementação. Você sai com o sorriso final.' }, { number: '05', title: 'Acompanhamento.', body: 'Revisão em 1-2 semanas. Manutenção semestral. Bem cuidadas, duram 10-15 anos ou mais.' }] },
    results: { eyebrow: 'O que esperar', title: 'O sorriso que', titleItalic: 'continua sendo seu.', paragraphs: ['O resultado mais elogiado é a naturalidade. Amigos sabem que algo mudou mas não conseguem apontar o quê.', 'Quando ninguém pergunta "o que você fez nos dentes?", o trabalho foi bem feito.'], moments: [{ title: 'A foto sem ajuste digital.', body: 'Você posta sem editar. E parece exatamente com você, melhor.' }, { title: 'O elogio que não menciona dentes.', body: 'Você está bonito. Está descansado. Está diferente.' }, { title: 'A rotina normal.', body: 'Comer, escovar, falar — como se sempre tivessem estado ali.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Custo, prazo,', titleItalic: 'e o que define os dois.', paragraphs: ['Facetas são tratamento estético de alto investimento. O processo completo leva 4 a 8 semanas.', 'O número de facetas (4 a 10) define a maior parte do custo.'], factors: ['Quantidade de facetas.', 'Material escolhido.', 'Tratamentos preparatórios necessários.', 'Complexidade do caso.'], closing: 'Mock-ups e diagnósticos não obrigam fechamento. Você decide quando estiver pronto.' },
    faq: [{ question: 'Faceta é a mesma coisa que lente de contato?', answer: 'São termos quase sinônimos. Lente é ultrafina (<0,5mm), muitas vezes sem preparo. Na prática moderna, a maioria dos casos usa lentes.' }, { question: 'Preciso desgastar os dentes?', answer: 'Desgaste mínimo nas técnicas modernas. Em casos selecionados, sem preparo nenhum.' }, { question: 'Quanto tempo duram?', answer: '10 a 15 anos em média. Alguns casos superam 20 anos com manutenção.' }, { question: 'Posso comer normalmente?', answer: 'Sim. Porcelana de qualidade tem resistência comparável ao esmalte natural.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'O sorriso novo', bronzeItalic: 'começa no mock-up.', description: 'Antes de tocarmos em qualquer dente, você vê e aprova como ficará.' },
  },

  'clareamento': {
    metadata: { title: 'Clareamento dental | Biodonth', description: 'Clareamento dental supervisionado em Artur Alvim. Resultado visível em poucas sessões, sem agressão ao esmalte.' },
    hero: { eyebrow: 'Tratamento \u2022 Clareamento', bronze: 'A diferença que', bronzeItalic: 'aparece em fotos.', description: 'Melhor relação entre custo, tempo e impacto visual. Em poucas sessões, dentes mais claros — sem desgastar nada.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'o clareamento ajuda.', intro: 'Os dentes escurecem com o tempo. Clareamento é a primeira escolha quando o que incomoda é a cor:', signals: ['Dentes que amareleceram com o tempo.', 'Consumo regular de café, vinho, chá.', 'Upgrade estético rápido antes de evento importante.', 'Você quer só cor mais clara, não mudança de forma.'], bridge: 'Clareamento não funciona em manchas profundas ou restaurações antigas. A primeira consulta identifica o que vai responder.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Dois métodos,', titleItalic: 'frequentemente combinados.', intro: 'Consultório (gel de alta concentração) + caseiro (moldeira individual). Frequentemente combinamos os dois.', steps: [{ number: '01', title: 'Avaliação + profilaxia.', body: 'Confirmação de que o clareamento é indicado. Limpeza profunda prévia.' }, { number: '02', title: 'Sessão em consultório.', body: 'Gel de alta concentração, 2-3 ciclos de 15 min. Resultado visível após 1-3 sessões.' }, { number: '03', title: 'Moldeira individual.', body: 'Uso em casa por 4-8h/dia ou noite, por 7-14 dias. Prolonga e uniformiza o resultado.' }, { number: '04', title: 'Manutenção.', body: 'Resultado dura 1-3 anos. Sessões de reforço anuais mantêm indefinidamente.' }] },
    results: { eyebrow: 'O que esperar', title: 'A diferença', titleItalic: 'visível e mensurável.', paragraphs: ['Em média, 4 a 8 tons mais claros. O efeito muda a percepção do próprio rosto.', 'Olhos parecem mais despertos, pele mais uniforme, o sorriso aparece mais nas fotos.'], moments: [{ title: 'A primeira foto.', body: 'Você nota a diferença na tela do celular.' }, { title: 'O comentário inesperado.', body: '"Você parece descansado." "Mudou o cabelo?"' }, { title: 'O sorriso que escapa.', body: 'Você ri mais. Sem cobrir. Sem calcular.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'O tratamento estético', titleItalic: 'mais acessível.', paragraphs: ['Melhor relação custo-benefício da estética dental. Protocolo completo: 2 a 4 semanas.', 'Valor apresentado por escrito na primeira consulta, com parcelamento.'], factors: ['Protocolo escolhido.', 'Estado inicial dos dentes.', 'Sensibilidade prévia.', 'Necessidade de profilaxia antes.'], closing: 'Clareamento entrega resultado visível, rápido, sem alterar nada de irreversível.' },
    faq: [{ question: 'Agride o esmalte?', answer: 'Não, quando supervisionado com produtos regulamentados. O gel age sobre pigmentos, não sobre a estrutura.' }, { question: 'Vou sentir sensibilidade?', answer: 'Algum grau é comum (40-50% dos casos). Desaparece em 24-72h após o protocolo.' }, { question: 'Restaurações clareiam junto?', answer: 'Não. Pode ser necessário trocá-las depois para uniformizar.' }, { question: 'Quanto dura o resultado?', answer: '1-3 anos. Manutenção anual mantém indefinidamente.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'O clareamento', bronzeItalic: 'em quatro semanas.', description: 'Da primeira consulta ao resultado final, 2-4 semanas. Supervisionado, sem agredir esmalte.' },
  },

  'endodontia': {
    metadata: { title: 'Endodontia | Biodonth', description: 'Tratamento de canal em Artur Alvim — endodontia moderna com tecnologia, precisão e conforto.' },
    hero: { eyebrow: 'Tratamento \u2022 Endodontia', bronze: 'Salvar o dente', bronzeItalic: 'que ainda é seu.', description: 'Tratamento de canal moderno não é o que você lembra. É preciso, controlado e mais confortável do que a fama sugere.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'o canal é necessário.', intro: 'O tratamento de canal salva dentes que de outra forma seriam extraídos. Vale conversar quando:', signals: ['Dor espontânea, pulsante, que piora à noite.', 'Sensibilidade intensa ao quente que demora a passar.', 'Dente escurecido sem causa aparente.', 'Inchaço na gengiva próximo à raiz do dente.', 'Cárie profunda que atingiu o nervo.', 'Trauma dental — pancada que comprometeu a polpa.'], bridge: 'Nem toda dor de dente é canal. A avaliação clínica e radiográfica diferencia o que precisa de canal do que resolve de outro modo.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Canal na Biodonth,', titleItalic: 'sem o drama antigo.', intro: 'Instrumentos modernos, localizadores de ápice e anestesia eficiente tornam o procedimento previsível e confortável.', steps: [{ number: '01', title: 'Diagnóstico preciso.', body: 'Exame clínico, testes de vitalidade e radiografia periapical para confirmar a indicação.' }, { number: '02', title: 'Anestesia completa.', body: 'Anestesia local com técnica adequada. Você não sente o procedimento.' }, { number: '03', title: 'Acesso e limpeza.', body: 'Remoção do tecido comprometido. Limpeza e modelagem dos canais com instrumentos rotatórios.' }, { number: '04', title: 'Obturação.', body: 'Selamento dos canais com material biocompatível. Radiografia de confirmação.' }, { number: '05', title: 'Restauração definitiva.', body: 'O dente tratado precisa de restauração ou coroa para proteção de longo prazo.' }] },
    results: { eyebrow: 'O que esperar', title: 'O dente que', titleItalic: 'ficou no lugar.', paragraphs: ['O objetivo do canal é um só: manter o dente. Um dente tratado e bem restaurado funciona normalmente por anos.', 'A dor que trouxe você ao consultório desaparece. O dente volta a cumprir sua função sem chamar atenção.'], moments: [{ title: 'A noite sem dor.', body: 'Dormir inteiro. Sem acordar com pulsação. Sem analgésico na mesa de cabeceira.' }, { title: 'A mordida de volta.', body: 'O lado que você evitava volta ao serviço. Comer com normalidade.' }, { title: 'O dente preservado.', body: 'Em vez de espaço vazio e implante futuro — o seu próprio dente, restaurado.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Rápido, preciso,', titleItalic: 'previsível.', paragraphs: ['A maioria dos canais é concluída em 1 a 2 sessões de 60-90 minutos.', 'Investimento menor que a alternativa — extração seguida de implante e coroa.'], factors: ['Número de canais no dente (anteriores: 1, molares: 3-4).', 'Complexidade anatômica.', 'Necessidade de retratamento.', 'Tipo de restauração final (bloco ou coroa).'], closing: 'O diagnóstico na primeira consulta já indica se o canal é necessário e o que envolve.' },
    faq: [{ question: 'Canal dói?', answer: 'Com anestesia moderna, não. A dor que você sente é da infecção — o canal alivia essa dor.' }, { question: 'Quantas sessões?', answer: '1 a 2 na maioria dos casos. Infecções mais extensas podem precisar de sessão adicional.' }, { question: 'O dente fica fraco?', answer: 'Mais frágil sem polpa, sim. Por isso a restauração ou coroa é parte essencial do tratamento.' }, { question: 'Dura quanto tempo?', answer: 'Com restauração adequada e manutenção, o dente tratado pode durar décadas.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'A dor tem', bronzeItalic: 'solução.', description: 'Se o dente dói, a primeira consulta diagnostica e define o caminho. Quanto antes, mais simples.' },
  },

  'odontopediatria': {
    metadata: { title: 'Odontopediatria | Biodonth', description: 'Odontopediatria em Artur Alvim, com profissionais especializados no cuidado de bebês, crianças e adolescentes.' },
    hero: { eyebrow: 'Tratamento \u2022 Odontopediatria', bronze: 'A relação com', bronzeItalic: 'dentista, para a vida.', description: 'A primeira ida da criança ao dentista decide a relação que ela terá com o cuidado da boca pelo resto da vida.' },
    consider: { eyebrow: 'Quando levar', title: 'A primeira vez', titleItalic: 'é antes do problema.', intro: 'A primeira ida não é em resposta a um problema — é antes. Orientações da Sociedade Brasileira de Odontopediatria:', signals: ['Primeira consulta: 6 a 12 meses de idade, ou após o primeiro dente.', 'Em qualquer idade, se a criança nunca foi ao dentista.', 'Manchas brancas, escuras ou pontos suspeitos nos dentes.', 'Queixas de dor ou dificuldade para comer.', 'Hábitos a orientar: chupeta prolongada, sucção do dedo, respiração bucal.', 'Traumas — queda com batida na boca.'], bridge: 'A maioria das primeiras consultas não envolve procedimento. É conversa, orientação e acolhimento.' },
    approach: { eyebrow: 'Como atendemos', title: 'Uma consulta', titleItalic: 'que parece uma visita.', intro: 'Nosso protocolo é pensado para que cada criança saia querendo voltar.', steps: [{ number: '01', title: 'Primeira visita — só para conhecer.', body: 'Conversa com os pais, criança explora o consultório. Sem procedimentos.' }, { number: '02', title: 'Avaliação cuidadosa.', body: 'Quando a criança permite, exame clínico completo. Em bebês, no colo dos pais.' }, { number: '03', title: 'Orientação familiar.', body: 'Escovação, fio dental, alimentação, chupeta. Tudo escrito, com fotos.' }, { number: '04', title: 'Tratamentos, quando necessários.', body: 'Técnicas atraumáticas sempre que possível. Anestesia com gel tópico prévio.' }, { number: '05', title: 'Acompanhamento regular.', body: 'Visitas semestrais com avaliação, limpeza e flúor.' }] },
    results: { eyebrow: 'O que esperar', title: 'Um adulto que', titleItalic: 'cuida dos próprios dentes.', paragraphs: ['O resultado é visível 20 anos depois: adulto que vai ao dentista por iniciativa própria, escova sem cobrar.', 'A curto prazo: menos cárie, menos urgência, menos dor evitável. E criança que quer voltar.'], moments: [{ title: 'A consulta sem choro.', body: 'Pais aliviados. Criança sorrindo. Nenhum trauma a construir.' }, { title: 'A escovação autônoma.', body: 'A criança escova sozinha, com técnica, porque aprendeu na consulta.' }, { title: 'O retorno aos 12 anos.', body: 'Adolescente que vai sem reclamar — porque dentista nunca foi lugar ruim.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'O cuidado', titleItalic: 'que se paga em prevenção.', paragraphs: ['Custo equivalente a consulta adulta. Procedimentos preventivos são rápidos e previsíveis.', 'Cada cárie evitada custa muito menos que cada cárie tratada.'], factors: ['Idade e cooperação da criança.', 'Necessidade de procedimentos.', 'Frequência das consultas (semestrais).', 'Indicação de aparelho preventivo.'], closing: 'Na primeira consulta, os pais saem entendendo o plano de cuidado com prazos e valores transparentes.' },
    faq: [{ question: 'A partir de que idade?', answer: '6 a 12 meses, ou após o primeiro dente. Não há "cedo demais".' }, { question: 'Vai ter choro?', answer: 'Nem sempre. Crianças preparadas com tranquilidade pelos pais raramente choram.' }, { question: 'Posso ficar na sala?', answer: 'Sim, sempre. Os pais permanecem durante toda a consulta.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'Comece cedo,', bronzeItalic: 'comece bem.', description: 'A primeira visita do seu filho ao dentista é uma decisão maior do que parece. Aqui, ela é planejada para começar bem.' },
  },

  'protese': {
    metadata: { title: 'Prótese dentária | Biodonth', description: 'Próteses dentárias fixas e removíveis em Artur Alvim. Reposição com função e estética.' },
    hero: { eyebrow: 'Tratamento \u2022 Prótese', bronze: 'Dentes que', bronzeItalic: 'parecem seus.', description: 'Prótese moderna não parece prótese. Funciona como o dente que faltava, mostra como se sempre tivesse estado ali.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'a prótese é o caminho.', intro: 'Próteses repõem um, vários ou todos os dentes. Vale conversar quando:', signals: ['Dentes extraídos que você quer repor.', 'Prótese antiga que solta, machuca ou dificulta a fala.', 'Dente com canal que precisa de coroa.', 'Busca solução mais econômica que implante.', 'Implantes já instalados que precisam de coroas finais.'], bridge: 'Cada caso tem mais de uma opção. A primeira consulta apresenta alternativas com prós e contras.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Do molde', titleItalic: 'à instalação.', intro: 'Qualidade da prótese depende de: planejamento, material e precisão na execução.', steps: [{ number: '01', title: 'Avaliação clínica.', body: 'Análise dos dentes, mordida, gengiva e estruturas de suporte.' }, { number: '02', title: 'Opções + plano.', body: 'Cerâmica vs. metalocerâmica, fixa vs. removível. Plano escrito.' }, { number: '03', title: 'Preparo.', body: 'Desgaste mínimo para criar espaço. Sessão única, anestesia local.' }, { number: '04', title: 'Moldagem e cor.', body: 'Moldes precisos ou escaneamento digital. Escolha de cor sob luz natural.' }, { number: '05', title: 'Provisório.', body: 'Você sai com prótese provisória estética enquanto a definitiva é confeccionada.' }, { number: '06', title: 'Instalação definitiva.', body: 'Teste, ajuste de mordida, cementação. Você sai com a prótese final.' }, { number: '07', title: 'Acompanhamento.', body: 'Revisão em 1-2 semanas. Manutenção semestral. Duram 10-15+ anos.' }] },
    results: { eyebrow: 'O que esperar', title: 'O dente que', titleItalic: 'não chama atenção.', paragraphs: ['O melhor resultado é não ser percebida. Morde com firmeza, fala sem ajuste.', 'Próteses modernas em cerâmica de alta resistência se comportam como dentes naturais.'], moments: [{ title: 'A mordida segura.', body: 'Morder sem hesitar, sem favorecer um lado.' }, { title: 'A foto natural.', body: 'Sorrir direto para a câmera. A prótese não aparece.' }, { title: 'O esquecimento.', body: 'Não é mais "o dente que é prótese". É só "o meu dente".' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Variação ampla,', titleItalic: 'planejamento individual.', paragraphs: ['De uma coroa unitária a reabilitações extensas. Custo varia proporcionalmente.', 'Tempo: 2-4 semanas (unitária) a 2-3 meses (múltiplas peças).'], factors: ['Tipo de prótese.', 'Material.', 'Quantidade de peças.', 'Apoio em dente vs. implante.', 'Tratamentos preparatórios.'], closing: 'Decisão sem pressão, sempre com tempo para pensar.' },
    faq: [{ question: 'Cerâmica ou metalocerâmica?', answer: 'Depende da localização. Cerâmicas puras: estética superior para dentes anteriores. Metalocerâmica: excelente para posteriores, custo menor.' }, { question: 'Preciso tirar para dormir?', answer: 'Fixas ficam sempre. Removíveis convencionais: geralmente retiradas para higiene e descanso.' }, { question: 'Quanto tempo dura?', answer: 'Fixas: 10-15 anos. Removíveis: reembasamento a cada 5-7 anos.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'A prótese certa,', bronzeItalic: 'para o seu caso.', description: 'Cada caso tem alternativas. A primeira consulta apresenta as suas, com prós e contras, prazos e valores.' },
  },

  'cirurgias': {
    metadata: { title: 'Cirurgias orais | Biodonth', description: 'Cirurgias orais em Artur Alvim — extrações, cirurgias de siso, enxertos e procedimentos com planejamento e acompanhamento completo.' },
    hero: { eyebrow: 'Tratamento \u2022 Cirurgias', bronze: 'Quando o caso pede', bronzeItalic: 'precisão cirúrgica.', description: 'Cirurgia oral não precisa ser drama. Com planejamento, equipe preparada e acompanhamento, o procedimento é mais simples do que a ansiedade sugere.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Situações que', titleItalic: 'pedem intervenção.', intro: 'A cirurgia é indicada quando o tratamento conservador não resolve. Casos mais comuns:', signals: ['Sisos inclusos ou parcialmente erupcionados que causam dor ou infecção.', 'Dentes comprometidos que precisam de extração planejada.', 'Necessidade de enxerto ósseo para futuros implantes.', 'Lesões ou cistos que precisam de remoção.', 'Frenectomia — freio lingual ou labial que limita função.', 'Preparo cirúrgico para próteses ou ortodontia.'], bridge: 'Nem toda indicação cirúrgica é urgente. A avaliação define se há alternativa e qual o melhor momento.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Cirurgia planejada,', titleItalic: 'passo a passo.', intro: 'Cada procedimento segue protocolo com avaliação prévia, planejamento e acompanhamento pós-operatório.', steps: [{ number: '01', title: 'Avaliação e exames.', body: 'Exame clínico, radiografia panorâmica ou tomografia. Histórico médico completo.' }, { number: '02', title: 'Planejamento cirúrgico.', body: 'Explicação detalhada do procedimento, riscos, cuidados pré e pós. Plano escrito.' }, { number: '03', title: 'Procedimento.', body: 'Anestesia local, técnica atraumática quando possível. Tempo varia conforme complexidade.' }, { number: '04', title: 'Orientações pós-operatórias.', body: 'Instruções escritas: medicação, alimentação, repouso, sinais de alerta.' }, { number: '05', title: 'Acompanhamento.', body: 'Retorno em 7-10 dias para remoção de sutura e avaliação da cicatrização.' }] },
    results: { eyebrow: 'O que esperar', title: 'O problema resolvido,', titleItalic: 'a recuperação acompanhada.', paragraphs: ['A maioria dos pacientes volta às atividades normais em 2-3 dias. Desconforto controlado com medicação comum.', 'O pós-operatório bem orientado faz toda a diferença na recuperação.'], moments: [{ title: 'O siso que parou de incomodar.', body: 'Sem dor, sem infecção recorrente, sem a preocupação constante.' }, { title: 'O osso que voltou.', body: 'Enxerto cicatrizado, base pronta para o implante que antes não era possível.' }, { title: 'A função restaurada.', body: 'Língua livre, lábio solto, mordida corrigida — o que a cirurgia desbloqueou.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Proporcional', titleItalic: 'à complexidade.', paragraphs: ['De extrações simples a enxertos complexos — cada caso com seu investimento.', 'A maioria dos procedimentos é ambulatorial, em sessão única.'], factors: ['Tipo de procedimento.', 'Complexidade anatômica.', 'Necessidade de enxerto ou biomaterial.', 'Exames pré-operatórios.', 'Tempo de recuperação esperado.'], closing: 'O plano cirúrgico é apresentado com transparência — procedimento, valores, tempo de recuperação.' },
    faq: [{ question: 'Preciso arrancar o siso?', answer: 'Nem sempre. Sisos que erupcionaram corretamente e são higienizáveis podem ficar. A avaliação radiográfica define.' }, { question: 'A cirurgia dói?', answer: 'O procedimento é feito sob anestesia local — você não sente. No pós, desconforto moderado por 2-3 dias, controlado com analgésicos.' }, { question: 'Quanto tempo de repouso?', answer: 'Extrações simples: 24-48h. Procedimentos maiores: 3-5 dias. Atividade física: 7-10 dias.' }, { question: 'Posso fazer mais de uma extração na mesma sessão?', answer: 'Sim, quando indicado. Muitas vezes é mais confortável resolver tudo de uma vez.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'O planejamento vem', bronzeItalic: 'antes da cirurgia.', description: 'Nenhuma cirurgia acontece sem avaliação completa. A primeira consulta explica o que precisa ser feito e por quê.' },
  },

  'harmonizacao-orofacial': {
    metadata: { title: 'Harmonização facial | Biodonth', description: 'Harmonização facial em Artur Alvim — procedimentos estéticos faciais com olhar clínico de quem entende a anatomia por completo.' },
    hero: { eyebrow: 'Tratamento \u2022 HOF', bronze: 'O equilíbrio que', bronzeItalic: 'o rosto pede.', description: 'Harmonização feita por quem entende osso, músculo e proporção. Resultados naturais, planejados com precisão anatômica.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'a harmonização faz sentido.', intro: 'A harmonização orofacial trata proporção e equilíbrio. Vale conversar quando:', signals: ['Queixo retraído ou assimétrico que incomoda no perfil.', 'Lábios finos ou sem definição de contorno.', 'Sorriso gengival — excesso de gengiva ao sorrir.', 'Rugas e linhas de expressão ao redor da boca.', 'Bruxismo que causa dor e hipertrofia do masseter.', 'Desejo de complementar o resultado de tratamento dental estético.'], bridge: 'A harmonização não substitui tratamento dental — complementa. A avaliação define o que faz sentido para o seu rosto.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Estética com', titleItalic: 'critério clínico.', intro: 'O diferencial do dentista na harmonização é o conhecimento profundo da anatomia orofacial — osso, músculo, nervo.', steps: [{ number: '01', title: 'Avaliação facial.', body: 'Análise de proporções, simetria, perfil e relação com o sorriso. Fotos padronizadas.' }, { number: '02', title: 'Planejamento.', body: 'Definição dos procedimentos indicados, volumes, pontos de aplicação. Expectativas alinhadas.' }, { number: '03', title: 'Procedimento.', body: 'Aplicação em consultório, com anestesia tópica. Sessões de 30 a 60 minutos.' }, { number: '04', title: 'Resultado imediato.', body: 'Efeito visível na hora. Resultado definitivo em 7-14 dias após acomodação.' }, { number: '05', title: 'Acompanhamento.', body: 'Retorno em 15 dias para avaliação. Retoques quando necessários.' }] },
    results: { eyebrow: 'O que esperar', title: 'Natural,', titleItalic: 'nunca artificial.', paragraphs: ['O melhor resultado é quando as pessoas dizem que você parece bem — sem saber apontar o que mudou.', 'Harmonização bem feita não muda quem você é. Equilibra o que já estava ali.'], moments: [{ title: 'O perfil no espelho.', body: 'Proporção que faz sentido. Queixo, lábio, nariz — em harmonia.' }, { title: 'O sorriso sem excesso.', body: 'A gengiva não domina mais. O sorriso aparece na medida.' }, { title: 'A mandíbula relaxada.', body: 'Sem tensão, sem dor, sem apertar. O masseter descansou.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Sessão única,', titleItalic: 'manutenção periódica.', paragraphs: ['A maioria dos procedimentos é feita em sessão única. Resultado dura 6 a 18 meses conforme o produto.', 'Investimento proporcional às áreas tratadas e ao volume utilizado.'], factors: ['Áreas tratadas.', 'Volume de produto.', 'Tipo de procedimento (toxina, preenchimento, bioestimulador).', 'Necessidade de retoque.'], closing: 'A avaliação facial é o primeiro passo. Você sai sabendo o que faz sentido e o que não faz.' },
    faq: [{ question: 'É seguro fazer com dentista?', answer: 'O dentista é o profissional com formação mais completa em anatomia orofacial. Habilitação regulamentada pelo CFO.' }, { question: 'O resultado é permanente?', answer: 'Depende do procedimento. Toxina botulínica: 4-6 meses. Ácido hialurônico: 8-18 meses. Bioestimuladores: 12-24 meses.' }, { question: 'Dói?', answer: 'Anestesia tópica ou bloqueio local. Desconforto mínimo durante e após.' }, { question: 'Fica artificial?', answer: 'Quando bem planejado e executado, não. A naturalidade é o objetivo.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'O equilíbrio começa', bronzeItalic: 'na avaliação.', description: 'A avaliação facial mostra o que faz sentido para o seu rosto. Sem pressão, sem promessas exageradas.' },
  },

  'checkup': {
    metadata: { title: 'Check-up preventivo digital | Biodonth', description: 'Check-up dental completo em Artur Alvim — a consulta preventiva que antecipa problemas e mantém a saúde bucal em dia.' },
    hero: { eyebrow: 'Tratamento \u2022 Check-up', bronze: 'A consulta que', bronzeItalic: 'antecipa problemas.', description: 'O check-up dental é a visita mais importante do ano. Descobre cedo o que custa pouco — antes de virar o que custa caro.' },
    consider: { eyebrow: 'Quando agendar', title: 'Pelo menos', titleItalic: 'uma vez por ano.', intro: 'A recomendação é a cada 6 meses. Mas vale agendar especialmente quando:', signals: ['Última visita ao dentista há mais de 1 ano.', 'Sangramento ao escovar ou passar fio dental.', 'Sensibilidade que não existia antes.', 'Mau hálito recorrente.', 'Vai começar outro tratamento (implante, ortodontia, estética).', 'Quer simplesmente saber se está tudo bem.'], bridge: 'A maioria dos problemas bucais é silenciosa no início. O check-up é a forma de descobrir antes de doer.' },
    approach: { eyebrow: 'Como fazemos aqui', title: 'Check-up completo,', titleItalic: 'feito com tempo.', intro: 'Não é consulta de 15 minutos. É avaliação completa, com tempo para examinar, explicar e orientar.', steps: [{ number: '01', title: 'Anamnese.', body: 'Conversa sobre histórico, queixas, hábitos, medicações. O contexto importa.' }, { number: '02', title: 'Exame clínico completo.', body: 'Dente a dente, gengiva, mucosa, articulação, oclusão. Nada é pulado.' }, { number: '03', title: 'Exames complementares.', body: 'Radiografias quando indicadas. Sondagem periodontal. Fotos intraorais.' }, { number: '04', title: 'Limpeza profissional.', body: 'Remoção de tártaro e polimento. A limpeza que escova nenhuma alcança.' }, { number: '05', title: 'Devolutiva e plano.', body: 'Explicação clara do que foi encontrado. Se há algo a tratar, plano escrito com prioridades.' }] },
    results: { eyebrow: 'O que esperar', title: 'Tranquilidade', titleItalic: 'ou antecipação.', paragraphs: ['Na maioria das vezes, o check-up confirma que está tudo bem — e isso tem valor.', 'Quando encontra algo, encontra cedo. Cárie pequena, gengivite inicial, desgaste que ainda não dói. Tudo mais simples de resolver.'], moments: [{ title: 'A certeza de que está tudo bem.', body: 'Sair do dentista sabendo que não há surpresas. A tranquilidade que só a prevenção dá.' }, { title: 'A cárie que custou pouco.', body: 'Descoberta no início, restauração simples. Sem dor, sem canal, sem coroa.' }, { title: 'A boca limpa.', body: 'Dentes lisos, hálito fresco, gengiva rosada. A sensação de boca renovada.' }] },
    investment: { eyebrow: 'Investimento', title: 'O menor custo', titleItalic: 'da odontologia.', paragraphs: ['Check-up é o investimento mais barato que existe em saúde bucal.', 'Cada problema descoberto cedo custa uma fração do que custaria tarde.'], factors: ['Exames radiográficos necessários.', 'Estado da gengiva e acúmulo de tártaro.', 'Necessidade de encaminhamento para especialidades.'], closing: 'Valor fixo e previsível. Sem surpresas no investimento, com potencial de economizar muito.' },
    faq: [{ question: 'Com que frequência devo fazer?', answer: 'A cada 6 meses é o ideal. Pacientes de baixo risco: uma vez por ano pode ser suficiente.' }, { question: 'Inclui limpeza?', answer: 'Sim. O check-up na Biodonth inclui limpeza profissional (profilaxia) como parte da consulta.' }, { question: 'Quanto tempo leva?', answer: '45 a 60 minutos. Tempo suficiente para examinar tudo com calma.' }, { question: 'Preciso ter alguma queixa?', answer: 'Não. O check-up é justamente para quando você não tem queixa — e quer manter assim.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'A prevenção começa', bronzeItalic: 'com uma visita.', description: 'Sem grande compromisso, sem investimento alto. A consulta que mantém todo o resto funcionando.' },
  },

  'saude-gengiva': {
    metadata: { title: 'Periodontia | Biodonth', description: 'Tratamento periodontal em Artur Alvim — diagnóstico e tratamento de gengivite e periodontite.' },
    hero: { eyebrow: 'Tratamento \u2022 Saúde da gengiva', bronze: 'A gengiva é', bronzeItalic: 'o alicerce.', description: 'Antes de qualquer estética, antes de qualquer implante — a gengiva. Quando ela cai, o resto vem junto.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'a gengiva pede atenção.', intro: 'Doença periodontal é a principal causa de perda de dentes em adultos. Avança silenciosa:', signals: ['Gengiva que sangra na escovação ou fio dental.', 'Gengiva vermelha, inchada ou sensível.', 'Mau hálito recorrente.', 'Dentes que parecem "maiores" — gengiva retraindo.', 'Mobilidade em algum dente.', 'Acúmulo fácil de tártaro.', 'Histórico familiar de doença periodontal.', 'Fumante, diabético ou sob estresse crônico.'], bridge: 'Gengivite é reversível. Periodontite diagnosticada cedo é controlável. O fator decisivo é o tempo até o diagnóstico.' },
    approach: { eyebrow: 'Como tratamos', title: 'Periodontia', titleItalic: 'feita com critério.', intro: 'O tratamento se adapta ao estágio da doença. Abordagem cuidadosa com medições precisas.', steps: [{ number: '01', title: 'Avaliação periodontal.', body: 'Sondagem em 6 pontos por dente. Registro de sangramento, mobilidade e perda óssea.' }, { number: '02', title: 'Diagnóstico e classificação.', body: 'Saúde periodontal, gengivite ou periodontite (estágios I-IV). Cada um com tratamento próprio.' }, { number: '03', title: 'Raspagem e alisamento.', body: 'Remoção de tártaro subgengival com curetas e ultrassom. 1-4 sessões.' }, { number: '04', title: 'Reavaliação.', body: 'Nova sondagem em 4-6 semanas. Mais de 80% dos casos respondem bem sem cirurgia.' }, { number: '05', title: 'Cirurgia (quando necessária).', body: 'Acesso, enxertos gengivais ou regeneração tecidual guiada para casos avançados.' }, { number: '06', title: 'Manutenção — permanente.', body: 'Consultas a cada 3-4 meses com sondagem periódica. Periodontite é controlada, não curada.' }] },
    results: { eyebrow: 'O que esperar', title: 'A gengiva que', titleItalic: 'volta a ser invisível.', paragraphs: ['Gengiva saudável é gengiva que você não percebe. Não sangra, não dói, não chama atenção.', 'A longo prazo: preservação dos dentes. Pacientes com periodontite controlada mantêm os próprios dentes.'], moments: [{ title: 'Fio sem sangue.', body: 'Você passa o fio, retira branco. Sem o lembrete da inflamação.' }, { title: 'Hálito que não te lembra.', body: 'Falar perto de alguém sem cálculo automático sobre o cheiro.' }, { title: 'O dente que parou de pedir.', body: 'Voltou ao normal. Parou de chamar atenção.' }] },
    investment: { eyebrow: 'Investimento', title: 'Adaptado', titleItalic: 'ao estágio.', paragraphs: ['Gengivite: 1-2 sessões. Periodontite avançada: 4-6 sessões + possível cirurgia.', 'Diagnóstico precoce = tratamento simples = custo menor.'], factors: ['Estágio da doença.', 'Número de áreas afetadas.', 'Necessidade de cirurgia.', 'Fatores de risco (fumo, diabetes).', 'Frequência da manutenção.'], closing: 'A primeira consulta inclui sondagem completa, diagnóstico e plano com prazos e valores.' },
    faq: [{ question: 'Periodontite tem cura?', answer: 'Não no sentido estrito. Mas com tratamento adequado e manutenção, fica controlada. Em 80%+ dos casos, para sempre.' }, { question: 'Sangra ao passar fio. É grave?', answer: 'Sinal de gengivite — reversível em 1-2 semanas com limpeza profissional. Mas ignorada vira periodontite.' }, { question: 'Sou fumante. Adianta tratar?', answer: 'Adianta, mas resposta ao tratamento é pior enquanto fuma. Conversamos com honestidade sobre isso.' }],
    closing: { eyebrow: 'Próximos passos', bronze: 'O alicerce', bronzeItalic: 'começa na sondagem.', description: 'Antes de qualquer estética ou reabilitação, vale avaliar a gengiva. A primeira consulta inclui sondagem completa.' },
  },
};
