// PT-BR long-form persuasion content for /tratamentos/[slug] pages.
// 9 treatments x 7 sections each. Single source of truth.
// Voice: patient as protagonist; clinic supports transformation; "sem pressa" mechanism implicit.

export type TreatmentFaqItem = { question: string; answer: string };

export type TreatmentContent = {
  metadata: { title: string; description: string };
  hero: { eyebrow: string; bronze: string; bronzeItalic: string; description: string };
  consider: {
    eyebrow: string; title: string; titleItalic: string;
    intro: string; signals: string[]; bridge: string;
  };
  approach: {
    eyebrow: string; title: string; titleItalic: string;
    intro: string; steps: { number: string; title: string; body: string }[];
  };
  results: {
    eyebrow: string; title: string; titleItalic: string;
    paragraphs: string[];
    moments: { title: string; body: string }[];
  };
  investment: {
    eyebrow: string; title: string; titleItalic: string;
    paragraphs: string[]; factors: string[]; closing: string;
  };
  faq: TreatmentFaqItem[];
  closing: { eyebrow: string; bronze: string; bronzeItalic: string; description: string };
};

export const TREATMENTS_CONTENT: Record<string, TreatmentContent> = {
  'implantes-dentarios': {
    metadata: { title: 'Implantes dent\u00e1rios | Biodonth', description: 'Implantes dent\u00e1rios em Arthur Alvim, S\u00e3o Paulo. Reabilita\u00e7\u00e3o de dentes perdidos com planejamento integrado e acompanhamento de longo prazo.' },
    hero: { eyebrow: 'Tratamento \u2022 Implantes', bronze: 'O dente que voltou', bronzeItalic: 'a ser seu.', description: 'Implante dent\u00e1rio n\u00e3o \u00e9 pr\u00f3tese \u2014 \u00e9 raiz nova. O dente que substitui o que faltava se comporta como o dente que sempre esteve ali: morde, fala, dura.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'o implante \u00e9 o caminho.', intro: 'Implantes substituem dentes extraídos, perdidos por trauma, ou comprometidos. Vale conversar quando:', signals: ['Voc\u00ea evita morder com um dos lados porque h\u00e1 um espa\u00e7o vazio.', 'Voc\u00ea usa pr\u00f3tese remov\u00edvel h\u00e1 anos e gostaria de n\u00e3o tirar mais nada da boca para limpar.', 'Um dente foi extra\u00eddo e os vizinhos come\u00e7aram a inclinar para o espa\u00e7o vazio.', 'Voc\u00ea passou a falar diferente depois de perder um dente.', 'Tem uma ponte antiga que precisa ser refeita sem desgastar os dentes vizinhos.'], bridge: 'Nenhum desses sinais decide o tratamento sozinho. O que decide \u00e9 a avalia\u00e7\u00e3o completa, feita na primeira consulta, com tempo de sobra.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'O implante na Biodonth,', titleItalic: 'passo a passo.', intro: 'Cada etapa \u00e9 planejada antes da pr\u00f3xima come\u00e7ar \u2014 e nada \u00e9 apressado.', steps: [{ number: '01', title: 'Avalia\u00e7\u00e3o inicial completa.', body: 'Conversamos sobre seu hist\u00f3rico, h\u00e1bitos, expectativas. Exame cl\u00ednico completo e indica\u00e7\u00e3o de exames de imagem.' }, { number: '02', title: 'Planejamento integrado.', body: 'Implantodontista, periodontista e protesista discutem o caso juntos antes de qualquer proposta.' }, { number: '03', title: 'Apresenta\u00e7\u00e3o do plano.', body: 'Voc\u00ea recebe o plano escrito \u2014 etapas, prazos, valores, alternativas. Leva para casa, pensa com calma.' }, { number: '04', title: 'Preparo (se necess\u00e1rio).', body: 'Tratamento de gengiva, enxerto \u00f3sseo quando o osso \u00e9 insuficiente, ou extra\u00e7\u00f5es de dentes comprometidos.' }, { number: '05', title: 'Cirurgia do implante.', body: 'Cirurgia ambulatorial sob anestesia local. 30 a 90 minutos por implante. Maioria volta \u00e0s atividades no dia seguinte.' }, { number: '06', title: 'Osseointegra\u00e7\u00e3o.', body: 'O implante se funde ao osso em 3 a 6 meses. Voc\u00ea usa pr\u00f3tese provis\u00f3ria nesse per\u00edodo.' }, { number: '07', title: 'Coroa final.', body: 'Moldes, escolha de cor, instala\u00e7\u00e3o da coroa definitiva. A partir da\u00ed, voc\u00ea morde e sorri normalmente.' }, { number: '08', title: 'Manuten\u00e7\u00e3o de longo prazo.', body: 'Consultas a cada 6 meses. Pacientes que fazem manuten\u00e7\u00e3o mant\u00eam implantes por d\u00e9cadas.' }] },
    results: { eyebrow: 'O que esperar do resultado', title: 'O que muda na vida', titleItalic: 'depois do implante.', paragraphs: ['O resultado de um implante bem feito n\u00e3o \u00e9 est\u00e9tico \u2014 \u00e9 existencial. A boca volta a ter a fun\u00e7\u00e3o que tinha.', 'Voc\u00ea morde dos dois lados sem pensar. Fala sem perceber. Sorri sem cobrir.'], moments: [{ title: 'A ma\u00e7\u00e3, a carne, o p\u00e3o.', body: 'Comer volta a ser sobre o sabor, n\u00e3o sobre qual lado consegue mastigar.' }, { title: 'A foto da fam\u00edlia.', body: 'Voc\u00ea sorri inteiro. Sem pensar onde o sorriso encontra a falta.' }, { title: 'A conversa sem c\u00e1lculo.', body: 'Sem palavras evitadas, sem dist\u00e2ncia calculada da outra pessoa.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Quanto custa,', titleItalic: 'quanto tempo demora.', paragraphs: ['O investimento varia conforme a complexidade. N\u00e3o trabalhamos com pre\u00e7os padronizados porque cada caso \u00e9 diferente.', 'Na primeira consulta, voc\u00ea recebe o plano com valores discriminados e op\u00e7\u00f5es de parcelamento em at\u00e9 12 vezes.'], factors: ['Quantidade de implantes necess\u00e1rios.', 'Necessidade de enxerto \u00f3sseo.', 'Tipo de coroa final.', 'Marca e linha do implante.', 'Tempo total do tratamento (4 a 9 meses em geral).'], closing: 'N\u00e3o pressionamos decis\u00f5es na primeira consulta. Voc\u00ea leva o plano e volta quando estiver pronto.' },
    faq: [{ question: 'Implante d\u00f3i?', answer: 'A cirurgia \u00e9 feita sob anestesia local. No p\u00f3s, desconforto leve a moderado nas primeiras 48h, controlado com analg\u00e9sicos comuns.' }, { question: 'Quanto tempo do in\u00edcio ao fim?', answer: 'Casos simples: 4 a 6 meses. Com enxerto: 9 a 12 meses. A osseointegra\u00e7\u00e3o \u00e9 a etapa mais longa.' }, { question: 'Implante dura para sempre?', answer: 'Literatura mostra taxa de sucesso superior a 95% em 10 anos. Muitos casos passam de 25-30 anos com manuten\u00e7\u00e3o adequada.' }, { question: 'Posso fazer com pouco osso?', answer: 'Em muitos casos, sim \u2014 com enxerto \u00f3sseo pr\u00e9vio. A tomografia na avalia\u00e7\u00e3o mostra exatamente o cen\u00e1rio.' }, { question: 'Fico sem dente durante o tratamento?', answer: 'Em geral, n\u00e3o. Usamos pr\u00f3tese provis\u00f3ria est\u00e9tica durante a osseointegra\u00e7\u00e3o.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'O caminho come\u00e7a', bronzeItalic: 'com uma conversa.', description: 'Implante \u00e9 decis\u00e3o grande. Por isso a primeira consulta tem tempo de sobra. Para que voc\u00ea saia entendendo o que precisa, com um plano na m\u00e3o.' },
  },

  'ortodontia': {
    metadata: { title: 'Ortodontia | Biodonth', description: 'Tratamento ortod\u00f4ntico em Arthur Alvim \u2014 aparelho fixo discreto ou alinhadores transparentes, com planejamento integrado.' },
    hero: { eyebrow: 'Tratamento \u2022 Ortodontia', bronze: 'Dentes no lugar.', bronzeItalic: 'Sem virar identidade.', description: 'Aparelho n\u00e3o precisa entrar antes de voc\u00ea na sala. Hoje h\u00e1 mais de uma forma de alinhar dentes.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'a ortodontia faz diferen\u00e7a.', intro: 'Ortodontia n\u00e3o \u00e9 s\u00f3 est\u00e9tica \u2014 \u00e9 sa\u00fade bucal, fun\u00e7\u00e3o e autoestima. Vale conversar quando:', signals: ['Dentes apinhados que dificultam escova\u00e7\u00e3o e fio dental.', 'Mordida que "trava" \u2014 os dentes n\u00e3o se encaixam corretamente.', 'Espa\u00e7o entre os dentes que incomoda ou cresceu com o tempo.', 'Mordida cruzada, aberta ou profunda.', 'Dor nas articula\u00e7\u00f5es da mand\u00edbula, dores de cabe\u00e7a ou ranger noturno.'], bridge: 'A primeira consulta inclui an\u00e1lise completa do sorriso, mordida e rela\u00e7\u00e3o dos maxilares.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Dois caminhos,', titleItalic: 'a mesma destina\u00e7\u00e3o.', intro: 'Aparelho fixo ou alinhadores transparentes \u2014 a melhor via depende do seu caso, estilo de vida e cronograma.', steps: [{ number: '01', title: 'Avalia\u00e7\u00e3o inicial.', body: 'An\u00e1lise dos dentes, mordida e articula\u00e7\u00f5es. Fotos, radiografias e escaneamento digital quando indicado.' }, { number: '02', title: 'Apresenta\u00e7\u00e3o das op\u00e7\u00f5es.', body: 'Plano com as vias vi\u00e1veis \u2014 aparelho met\u00e1lico, est\u00e9tico ou alinhadores \u2014 com prazos e valores.' }, { number: '03', title: 'Instala\u00e7\u00e3o ou in\u00edcio dos alinhadores.', body: 'Aparelho fixo: 60-90 minutos, indolor. Alinhadores: primeira sequ\u00eancia com instru\u00e7\u00f5es de uso.' }, { number: '04', title: 'Acompanhamento.', body: 'Fixo: consultas mensais. Alinhadores: a cada 6-10 semanas. Fotos comparativas mostram evolu\u00e7\u00e3o.' }, { number: '05', title: 'Finaliza\u00e7\u00e3o e conten\u00e7\u00e3o.', body: 'Remo\u00e7\u00e3o do aparelho e instala\u00e7\u00e3o de conten\u00e7\u00f5es para evitar recidiva.' }] },
    results: { eyebrow: 'O que esperar', title: 'Mais do que', titleItalic: 'dentes alinhados.', paragraphs: ['Resultado vis\u00edvel: sorriso sim\u00e9trico e fotog\u00eanico. Resultado invis\u00edvel: escova\u00e7\u00e3o mais eficaz, menos c\u00e1ries, gengiva mais saud\u00e1vel.', 'Para a maioria dos adultos, h\u00e1 ainda a confian\u00e7a recuperada de sorrir aberto e ser fotografado.'], moments: [{ title: 'O primeiro selfie de boca aberta.', body: 'Sem c\u00e1lculo. Sem \u00e2ngulo. Apenas o sorriso.' }, { title: 'A escova\u00e7\u00e3o que finalmente alcan\u00e7a.', body: 'Fio dental que desliza, cantos limpos, retorno ao dentista sem c\u00e1rie nova.' }, { title: 'A mordida que para de te lembrar.', body: 'Sem trinco, sem tens\u00e3o na ATM, sem dor de cabe\u00e7a.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Tempo e custo,', titleItalic: 'sem rodeios.', paragraphs: ['Tempo: 12 a 36 meses, dependendo da complexidade. Casos leves: 6-9 meses.', 'Custo varia conforme o caminho. Parcelamento durante todo o tratamento \u2014 voc\u00ea paga conforme as consultas acontecem.'], factors: ['Tipo de aparelho ou alinhador.', 'Complexidade do caso.', 'Procedimentos auxiliares (extra\u00e7\u00f5es, mini-implantes).', 'Ades\u00e3o do paciente (alinhadores: 20-22h/dia).', 'Idade (adultos demoram um pouco mais).'], closing: 'Na primeira consulta, voc\u00ea sai com ambos os caminhos apresentados lado a lado, quando vi\u00e1veis.' },
    faq: [{ question: 'Adulto pode fazer aparelho?', answer: 'Sim. Mais de 35% dos pacientes ortod\u00f4nticos no Brasil s\u00e3o adultos. Resultados igualmente previs\u00edveis e duradouros.' }, { question: 'Alinhador serve para qualquer caso?', answer: 'N\u00e3o. Funciona bem para apinhamento leve a moderado. Casos complexos se beneficiam mais do fixo.' }, { question: 'Atrapalha a fala?', answer: 'Nos primeiros 5-10 dias, adapta\u00e7\u00e3o leve. Depois, a fala se ajusta completamente.' }, { question: 'Vou precisar de conten\u00e7\u00e3o para sempre?', answer: 'Algum tipo de conten\u00e7\u00e3o \u00e9 recomendado permanentemente. Os dentes t\u00eam tend\u00eancia natural a se moverem.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'A consulta', bronzeItalic: 'come\u00e7a o caminho.', description: 'Voc\u00ea sai da primeira consulta sabendo quais op\u00e7\u00f5es servem, quanto tempo cada uma leva, e quanto custa.' },
  },

  'facetas': {
    metadata: { title: 'Facetas em porcelana | Biodonth', description: 'Facetas e lentes de contato dentais em porcelana em Arthur Alvim, planejadas no detalhe.' },
    hero: { eyebrow: 'Tratamento \u2022 Facetas', bronze: 'O sorriso que', bronzeItalic: 'ningu\u00e9m percebe.', description: 'Faceta bem feita n\u00e3o \u00e9 "trabalho de dentista". \u00c9 o seu sorriso, naturalmente melhor.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'as facetas fazem sentido.', intro: 'Facetas corrigem cor, forma, tamanho ou pequenos desalinhamentos. Vale considerar quando:', signals: ['Cor que n\u00e3o responde a clareamento.', 'Forma dos dentes que incomoda \u2014 desgaste, bordas irregulares.', 'Diastemas discretos que voc\u00ea prefere fechar sem ortodontia.', 'Pequenas fraturas ou imperfeições que chamam aten\u00e7\u00e3o.', 'Voc\u00ea quer o passo final ap\u00f3s ortodontia ou clareamento.'], bridge: 'Em muitos casos, clareamento ou ortodontia resolvem com menos desgaste. A primeira consulta serve para essa avalia\u00e7\u00e3o honesta.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'O caminho at\u00e9', titleItalic: 'a faceta final.', intro: 'A diferen\u00e7a entre faceta natural e faceta "de novela" est\u00e1 no planejamento.', steps: [{ number: '01', title: 'Avalia\u00e7\u00e3o + refer\u00eancias.', body: 'Fotos, escaneamento, conversa sobre o que voc\u00ea gosta no seu sorriso e o que mudaria.' }, { number: '02', title: 'Mock-up + ensaio.', body: 'Simula\u00e7\u00e3o direta sobre seus dentes com resina tempor\u00e1ria. Voc\u00ea v\u00ea e sente antes de qualquer coisa irrevers\u00edvel.' }, { number: '03', title: 'Preparo m\u00ednimo.', body: 'Menos de 0,5mm de esmalte. Em alguns casos, sem preparo nenhum. Voc\u00ea sai com provis\u00f3rias est\u00e9ticas.' }, { number: '04', title: 'Instala\u00e7\u00e3o definitiva.', body: 'Em ~90 minutos: teste, ajuste de cor, cementa\u00e7\u00e3o. Voc\u00ea sai com o sorriso final.' }, { number: '05', title: 'Acompanhamento.', body: 'Revis\u00e3o em 1-2 semanas. Manuten\u00e7\u00e3o semestral. Bem cuidadas, duram 10-15 anos ou mais.' }] },
    results: { eyebrow: 'O que esperar', title: 'O sorriso que', titleItalic: 'continua sendo seu.', paragraphs: ['O resultado mais elogiado \u00e9 a naturalidade. Amigos sabem que algo mudou mas n\u00e3o conseguem apontar o qu\u00ea.', 'Quando ningu\u00e9m pergunta "o que voc\u00ea fez nos dentes?", o trabalho foi bem feito.'], moments: [{ title: 'A foto sem ajuste digital.', body: 'Voc\u00ea posta sem editar. E parece exatamente com voc\u00ea, melhor.' }, { title: 'O elogio que n\u00e3o menciona dentes.', body: 'Voc\u00ea est\u00e1 bonito. Est\u00e1 descansado. Est\u00e1 diferente.' }, { title: 'A rotina normal.', body: 'Comer, escovar, falar \u2014 como se sempre tivessem estado ali.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Custo, prazo,', titleItalic: 'e o que define os dois.', paragraphs: ['Facetas s\u00e3o tratamento est\u00e9tico de alto investimento. O processo completo leva 4 a 8 semanas.', 'O n\u00famero de facetas (4 a 10) define a maior parte do custo.'], factors: ['Quantidade de facetas.', 'Material escolhido.', 'Tratamentos preparat\u00f3rios necess\u00e1rios.', 'Complexidade do caso.'], closing: 'Mock-ups e diagn\u00f3sticos n\u00e3o obrigam fechamento. Voc\u00ea decide quando estiver pronto.' },
    faq: [{ question: 'Faceta \u00e9 a mesma coisa que lente de contato?', answer: 'S\u00e3o termos quase sin\u00f4nimos. Lente \u00e9 ultrafina (<0,5mm), muitas vezes sem preparo. Na pr\u00e1tica moderna, a maioria dos casos usa lentes.' }, { question: 'Preciso desgastar os dentes?', answer: 'Desgaste m\u00ednimo nas t\u00e9cnicas modernas. Em casos selecionados, sem preparo nenhum.' }, { question: 'Quanto tempo duram?', answer: '10 a 15 anos em m\u00e9dia. Alguns casos superam 20 anos com manuten\u00e7\u00e3o.' }, { question: 'Posso comer normalmente?', answer: 'Sim. Porcelana de qualidade tem resist\u00eancia compar\u00e1vel ao esmalte natural.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'O sorriso novo', bronzeItalic: 'come\u00e7a no mock-up.', description: 'Antes de tocarmos em qualquer dente, voc\u00ea v\u00ea e aprova como ficar\u00e1.' },
  },

  'clareamento': {
    metadata: { title: 'Clareamento dental | Biodonth', description: 'Clareamento dental supervisionado em Arthur Alvim. Resultado vis\u00edvel em poucas sess\u00f5es, sem agress\u00e3o ao esmalte.' },
    hero: { eyebrow: 'Tratamento \u2022 Clareamento', bronze: 'A diferen\u00e7a que', bronzeItalic: 'aparece em fotos.', description: 'Melhor rela\u00e7\u00e3o entre custo, tempo e impacto visual. Em poucas sess\u00f5es, dentes mais claros \u2014 sem desgastar nada.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'o clareamento ajuda.', intro: 'Os dentes escurecem com o tempo. Clareamento \u00e9 a primeira escolha quando o que incomoda \u00e9 a cor:', signals: ['Dentes que amareleceram com o tempo.', 'Consumo regular de caf\u00e9, vinho, ch\u00e1.', 'Upgrade est\u00e9tico r\u00e1pido antes de evento importante.', 'Voc\u00ea quer s\u00f3 cor mais clara, n\u00e3o mudan\u00e7a de forma.'], bridge: 'Clareamento n\u00e3o funciona em manchas profundas ou restaura\u00e7\u00f5es antigas. A primeira consulta identifica o que vai responder.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Dois m\u00e9todos,', titleItalic: 'frequentemente combinados.', intro: 'Consult\u00f3rio (gel de alta concentra\u00e7\u00e3o) + caseiro (moldeira individual). Frequentemente combinamos os dois.', steps: [{ number: '01', title: 'Avalia\u00e7\u00e3o + profilaxia.', body: 'Confirma\u00e7\u00e3o de que o clareamento \u00e9 indicado. Limpeza profunda pr\u00e9via.' }, { number: '02', title: 'Sess\u00e3o em consult\u00f3rio.', body: 'Gel de alta concentra\u00e7\u00e3o, 2-3 ciclos de 15 min. Resultado vis\u00edvel ap\u00f3s 1-3 sess\u00f5es.' }, { number: '03', title: 'Moldeira individual.', body: 'Uso em casa por 4-8h/dia ou noite, por 7-14 dias. Prolonga e uniformiza o resultado.' }, { number: '04', title: 'Manuten\u00e7\u00e3o.', body: 'Resultado dura 1-3 anos. Sess\u00f5es de refor\u00e7o anuais mant\u00eam indefinidamente.' }] },
    results: { eyebrow: 'O que esperar', title: 'A diferen\u00e7a', titleItalic: 'vis\u00edvel e mensur\u00e1vel.', paragraphs: ['Em m\u00e9dia, 4 a 8 tons mais claros. O efeito muda a percep\u00e7\u00e3o do pr\u00f3prio rosto.', 'Olhos parecem mais despertos, pele mais uniforme, o sorriso aparece mais nas fotos.'], moments: [{ title: 'A primeira foto.', body: 'Voc\u00ea nota a diferen\u00e7a na tela do celular.' }, { title: 'O coment\u00e1rio inesperado.', body: '"Voc\u00ea parece descansado." "Mudou o cabelo?"' }, { title: 'O sorriso que escapa.', body: 'Voc\u00ea ri mais. Sem cobrir. Sem calcular.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'O tratamento est\u00e9tico', titleItalic: 'mais acess\u00edvel.', paragraphs: ['Melhor rela\u00e7\u00e3o custo-benef\u00edcio da est\u00e9tica dental. Protocolo completo: 2 a 4 semanas.', 'Valor apresentado por escrito na primeira consulta, com parcelamento.'], factors: ['Protocolo escolhido.', 'Estado inicial dos dentes.', 'Sensibilidade pr\u00e9via.', 'Necessidade de profilaxia antes.'], closing: 'Clareamento entrega resultado vis\u00edvel, r\u00e1pido, sem alterar nada de irrevers\u00edvel.' },
    faq: [{ question: 'Agride o esmalte?', answer: 'N\u00e3o, quando supervisionado com produtos regulamentados. O gel age sobre pigmentos, n\u00e3o sobre a estrutura.' }, { question: 'Vou sentir sensibilidade?', answer: 'Algum grau \u00e9 comum (40-50% dos casos). Desaparece em 24-72h ap\u00f3s o protocolo.' }, { question: 'Restaura\u00e7\u00f5es clareiam junto?', answer: 'N\u00e3o. Pode ser necess\u00e1rio troc\u00e1-las depois para uniformizar.' }, { question: 'Quanto dura o resultado?', answer: '1-3 anos. Manuten\u00e7\u00e3o anual mant\u00e9m indefinidamente.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'O clareamento', bronzeItalic: 'em quatro semanas.', description: 'Da primeira consulta ao resultado final, 2-4 semanas. Supervisionado, sem agredir esmalte.' },
  },

  'reabilitacao-oral': {
    metadata: { title: 'Reabilita\u00e7\u00e3o oral | Biodonth', description: 'Reabilita\u00e7\u00e3o oral completa em Arthur Alvim \u2014 quando a boca precisa ser refeita por inteiro, etapa por etapa.' },
    hero: { eyebrow: 'Tratamento \u2022 Reabilita\u00e7\u00e3o oral', bronze: 'A boca volta', bronzeItalic: 'a ser sua.', description: 'Tratamento integral quando muitos dentes precisam ser refeitos. O caminho mais longo \u2014 e o mais transformador.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: '\u00e9 hora de refazer.', intro: 'Reabilita\u00e7\u00e3o envolve m\u00faltiplas especialidades. Vale o caminho quando:', signals: ['Perdeu m\u00faltiplos dentes e a mastiga\u00e7\u00e3o est\u00e1 comprometida.', 'Maioria dos dentes com restaura\u00e7\u00f5es antigas comprometidas.', 'Usa pr\u00f3teses remov\u00edveis e quer migrar para solu\u00e7\u00f5es fixas.', 'Mordida colapsada, dentes desgastados, dores na ATM.', 'Cada especialista d\u00e1 uma proposta que n\u00e3o conversa com as outras.'], bridge: '\u00c9 decis\u00e3o para uma primeira conversa em uma s\u00e9rie de conversas, todas com tempo de sobra.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Reabilita\u00e7\u00e3o', titleItalic: 'verdadeiramente integrada.', intro: 'Em vez de 4 cl\u00ednicas diferentes, a Biodonth faz o planejamento em uma \u00fanica sala, com a equipe sentada junto.', steps: [{ number: '01', title: 'Avalia\u00e7\u00e3o inicial.', body: 'Exames completos: panor\u00e2mica, tomografia, fotos, escaneamento intraoral.' }, { number: '02', title: 'Planejamento em equipe.', body: 'Implantodontia, pr\u00f3tese, periodontia, ortodontia discutem juntos. Plano \u00fanico.' }, { number: '03', title: 'Apresenta\u00e7\u00e3o do plano.', body: 'Estado atual, objetivo final, cada etapa, ordem, prazos e custos discriminados.' }, { number: '04', title: 'Preparos.', body: 'Tratamento de gengiva, extra\u00e7\u00f5es, canais, enxertos \u2014 cada um na sua ordem.' }, { number: '05', title: 'Implantes.', body: 'Coloca\u00e7\u00e3o dos implantes, osseointegra\u00e7\u00e3o, pr\u00f3teses provis\u00f3rias.' }, { number: '06', title: 'Pr\u00f3teses definitivas.', body: 'Coroas, pontes ou protocolos sobre implantes. V\u00e1rias consultas para provas e ajustes.' }, { number: '07', title: 'Acompanhamento.', body: 'Manuten\u00e7\u00e3o a cada 6 meses. Bem cuidada, acompanha voc\u00ea por d\u00e9cadas.' }] },
    results: { eyebrow: 'O que esperar', title: 'O que muda', titleItalic: 'quando a boca volta.', paragraphs: ['Pacientes descrevem "voltei a viver", "lembrei como era", "n\u00e3o percebia o quanto pesava".', 'Comer volta a ser sobre sabor. Falar, sobre o que se diz. Sorrir, uma resposta natural.'], moments: [{ title: 'A refei\u00e7\u00e3o em sil\u00eancio.', body: 'Comer sem pensar. Sem favorecer um lado. O sil\u00eancio do al\u00edvio.' }, { title: 'A risada inteira.', body: 'O riso solto, sem m\u00e3o na frente, pela primeira vez em anos.' }, { title: 'A foto onde voc\u00ea reconhece.', body: 'A pessoa que voltou \u00e0s fotos \u00e9 voc\u00ea. S\u00f3 mais cuidada.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Um investimento longo,', titleItalic: 'feito por etapas.', paragraphs: ['Investimento proporcional \u00e0 transforma\u00e7\u00e3o. Dura 12 a 24 meses.', 'Pagamento por etapas \u2014 voc\u00ea paga conforme cada fase \u00e9 executada.'], factors: ['Quantidade de implantes.', 'Enxertos \u00f3sseos.', 'Tipo das pr\u00f3teses finais.', 'Tratamentos preparat\u00f3rios.', 'Tempo total.'], closing: 'N\u00e3o h\u00e1 press\u00e3o para fechar. A maioria dos pacientes decide semanas depois da apresenta\u00e7\u00e3o do plano.' },
    faq: [{ question: 'Quanto tempo leva?', answer: '12 a 24 meses. Casos complexos: at\u00e9 30 meses. Cada etapa tem tempo biol\u00f3gico pr\u00f3prio.' }, { question: 'Fico com pr\u00f3tese remov\u00edvel?', answer: 'Em quase nenhum caso voc\u00ea fica sem dentes. Usamos provis\u00f3rias est\u00e9ticas do come\u00e7o ao fim.' }, { question: 'Vale na minha idade?', answer: 'Feita em pacientes de 30 a 85+ anos. A pergunta n\u00e3o \u00e9 idade \u2014 \u00e9 qualidade de vida.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'O plano completo', bronzeItalic: 'come\u00e7a com escuta.', description: 'A primeira consulta de reabilita\u00e7\u00e3o \u00e9, antes de tudo, uma conversa longa. O plano vem depois.' },
  },

  'odontopediatria': {
    metadata: { title: 'Odontopediatria | Biodonth', description: 'Odontopediatria em Arthur Alvim, com profissionais especializados no cuidado de beb\u00eas, crian\u00e7as e adolescentes.' },
    hero: { eyebrow: 'Tratamento \u2022 Odontopediatria', bronze: 'A rela\u00e7\u00e3o com', bronzeItalic: 'dentista, para a vida.', description: 'A primeira ida da crian\u00e7a ao dentista decide a rela\u00e7\u00e3o que ela ter\u00e1 com o cuidado da boca pelo resto da vida.' },
    consider: { eyebrow: 'Quando levar', title: 'A primeira vez', titleItalic: '\u00e9 antes do problema.', intro: 'A primeira ida n\u00e3o \u00e9 em resposta a um problema \u2014 \u00e9 antes. Orienta\u00e7\u00f5es da Sociedade Brasileira de Odontopediatria:', signals: ['Primeira consulta: 6 a 12 meses de idade, ou ap\u00f3s o primeiro dente.', 'Em qualquer idade, se a crian\u00e7a nunca foi ao dentista.', 'Manchas brancas, escuras ou pontos suspeitos nos dentes.', 'Queixas de dor ou dificuldade para comer.', 'H\u00e1bitos a orientar: chupeta prolongada, suc\u00e7\u00e3o do dedo, respira\u00e7\u00e3o bucal.', 'Traumas \u2014 queda com batida na boca.'], bridge: 'A maioria das primeiras consultas n\u00e3o envolve procedimento. \u00c9 conversa, orienta\u00e7\u00e3o e acolhimento.' },
    approach: { eyebrow: 'Como atendemos', title: 'Uma consulta', titleItalic: 'que parece uma visita.', intro: 'Nosso protocolo \u00e9 pensado para que cada crian\u00e7a saia querendo voltar.', steps: [{ number: '01', title: 'Primeira visita \u2014 s\u00f3 para conhecer.', body: 'Conversa com os pais, crian\u00e7a explora o consult\u00f3rio. Sem procedimentos.' }, { number: '02', title: 'Avalia\u00e7\u00e3o cuidadosa.', body: 'Quando a crian\u00e7a permite, exame cl\u00ednico completo. Em beb\u00eas, no colo dos pais.' }, { number: '03', title: 'Orienta\u00e7\u00e3o familiar.', body: 'Escova\u00e7\u00e3o, fio dental, alimenta\u00e7\u00e3o, chupeta. Tudo escrito, com fotos.' }, { number: '04', title: 'Tratamentos, quando necess\u00e1rios.', body: 'T\u00e9cnicas atraum\u00e1ticas sempre que poss\u00edvel. Anestesia com gel t\u00f3pico pr\u00e9vio.' }, { number: '05', title: 'Acompanhamento regular.', body: 'Visitas semestrais com avalia\u00e7\u00e3o, limpeza e fl\u00faor.' }] },
    results: { eyebrow: 'O que esperar', title: 'Um adulto que', titleItalic: 'cuida dos pr\u00f3prios dentes.', paragraphs: ['O resultado \u00e9 vis\u00edvel 20 anos depois: adulto que vai ao dentista por iniciativa pr\u00f3pria, escova sem cobrar.', 'A curto prazo: menos c\u00e1rie, menos urg\u00eancia, menos dor evit\u00e1vel. E crian\u00e7a que quer voltar.'], moments: [{ title: 'A consulta sem choro.', body: 'Pais aliviados. Crian\u00e7a sorrindo. Nenhum trauma a construir.' }, { title: 'A escova\u00e7\u00e3o aut\u00f4noma.', body: 'A crian\u00e7a escova sozinha, com t\u00e9cnica, porque aprendeu na consulta.' }, { title: 'O retorno aos 12 anos.', body: 'Adolescente que vai sem reclamar \u2014 porque dentista nunca foi lugar ruim.' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'O cuidado', titleItalic: 'que se paga em preven\u00e7\u00e3o.', paragraphs: ['Custo equivalente a consulta adulta. Procedimentos preventivos s\u00e3o r\u00e1pidos e previs\u00edveis.', 'Cada c\u00e1rie evitada custa muito menos que cada c\u00e1rie tratada.'], factors: ['Idade e coopera\u00e7\u00e3o da crian\u00e7a.', 'Necessidade de procedimentos.', 'Frequ\u00eancia das consultas (semestrais).', 'Indica\u00e7\u00e3o de aparelho preventivo.'], closing: 'Na primeira consulta, os pais saem entendendo o plano de cuidado com prazos e valores transparentes.' },
    faq: [{ question: 'A partir de que idade?', answer: '6 a 12 meses, ou ap\u00f3s o primeiro dente. N\u00e3o h\u00e1 "cedo demais".' }, { question: 'Vai ter choro?', answer: 'Nem sempre. Crian\u00e7as preparadas com tranquilidade pelos pais raramente choram.' }, { question: 'Posso ficar na sala?', answer: 'Sim, sempre. Os pais permanecem durante toda a consulta.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'Comece cedo,', bronzeItalic: 'comece bem.', description: 'A primeira visita do seu filho ao dentista \u00e9 uma decis\u00e3o maior do que parece. Aqui, ela \u00e9 planejada para come\u00e7ar bem.' },
  },

  'protese': {
    metadata: { title: 'Pr\u00f3tese dent\u00e1ria | Biodonth', description: 'Pr\u00f3teses dent\u00e1rias fixas e remov\u00edveis em Arthur Alvim. Reposi\u00e7\u00e3o com fun\u00e7\u00e3o e est\u00e9tica.' },
    hero: { eyebrow: 'Tratamento \u2022 Pr\u00f3tese', bronze: 'Dentes que', bronzeItalic: 'parecem seus.', description: 'Pr\u00f3tese moderna n\u00e3o parece pr\u00f3tese. Funciona como o dente que faltava, mostra como se sempre tivesse estado ali.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'a pr\u00f3tese \u00e9 o caminho.', intro: 'Pr\u00f3teses repõem um, v\u00e1rios ou todos os dentes. Vale conversar quando:', signals: ['Dentes extra\u00eddos que voc\u00ea quer repor.', 'Pr\u00f3tese antiga que solta, machuca ou dificulta a fala.', 'Dente com canal que precisa de coroa.', 'Busca solu\u00e7\u00e3o mais econ\u00f4mica que implante.', 'Implantes j\u00e1 instalados que precisam de coroas finais.'], bridge: 'Cada caso tem mais de uma op\u00e7\u00e3o. A primeira consulta apresenta alternativas com pr\u00f3s e contras.' },
    approach: { eyebrow: 'Como tratamos aqui', title: 'Do molde', titleItalic: '\u00e0 instala\u00e7\u00e3o.', intro: 'Qualidade da pr\u00f3tese depende de: planejamento, material e precis\u00e3o na execu\u00e7\u00e3o.', steps: [{ number: '01', title: 'Avalia\u00e7\u00e3o cl\u00ednica.', body: 'An\u00e1lise dos dentes, mordida, gengiva e estruturas de suporte.' }, { number: '02', title: 'Op\u00e7\u00f5es + plano.', body: 'Cer\u00e2mica vs. metalocer\u00e2mica, fixa vs. remov\u00edvel. Plano escrito.' }, { number: '03', title: 'Preparo.', body: 'Desgaste m\u00ednimo para criar espa\u00e7o. Sess\u00e3o \u00fanica, anestesia local.' }, { number: '04', title: 'Moldagem e cor.', body: 'Moldes precisos ou escaneamento digital. Escolha de cor sob luz natural.' }, { number: '05', title: 'Provis\u00f3rio.', body: 'Voc\u00ea sai com pr\u00f3tese provis\u00f3ria est\u00e9tica enquanto a definitiva \u00e9 confeccionada.' }, { number: '06', title: 'Instala\u00e7\u00e3o definitiva.', body: 'Teste, ajuste de mordida, cementa\u00e7\u00e3o. Voc\u00ea sai com a pr\u00f3tese final.' }, { number: '07', title: 'Acompanhamento.', body: 'Revis\u00e3o em 1-2 semanas. Manuten\u00e7\u00e3o semestral. Duram 10-15+ anos.' }] },
    results: { eyebrow: 'O que esperar', title: 'O dente que', titleItalic: 'n\u00e3o chama aten\u00e7\u00e3o.', paragraphs: ['O melhor resultado \u00e9 n\u00e3o ser percebida. Morde com firmeza, fala sem ajuste.', 'Pr\u00f3teses modernas em cer\u00e2mica de alta resist\u00eancia se comportam como dentes naturais.'], moments: [{ title: 'A mordida segura.', body: 'Morder sem hesitar, sem favorecer um lado.' }, { title: 'A foto natural.', body: 'Sorrir direto para a c\u00e2mera. A pr\u00f3tese n\u00e3o aparece.' }, { title: 'O esquecimento.', body: 'N\u00e3o \u00e9 mais "o dente que \u00e9 pr\u00f3tese". \u00c9 s\u00f3 "o meu dente".' }] },
    investment: { eyebrow: 'Investimento e tempo', title: 'Varia\u00e7\u00e3o ampla,', titleItalic: 'planejamento individual.', paragraphs: ['De uma coroa unit\u00e1ria a reabilita\u00e7\u00f5es extensas. Custo varia proporcionalmente.', 'Tempo: 2-4 semanas (unit\u00e1ria) a 2-3 meses (m\u00faltiplas pe\u00e7as).'], factors: ['Tipo de pr\u00f3tese.', 'Material.', 'Quantidade de pe\u00e7as.', 'Apoio em dente vs. implante.', 'Tratamentos preparat\u00f3rios.'], closing: 'Decis\u00e3o sem press\u00e3o, sempre com tempo para pensar.' },
    faq: [{ question: 'Cer\u00e2mica ou metalocer\u00e2mica?', answer: 'Depende da localiza\u00e7\u00e3o. Cer\u00e2micas puras: est\u00e9tica superior para dentes anteriores. Metalocer\u00e2mica: excelente para posteriores, custo menor.' }, { question: 'Preciso tirar para dormir?', answer: 'Fixas ficam sempre. Remov\u00edveis convencionais: geralmente retiradas para higiene e descanso.' }, { question: 'Quanto tempo dura?', answer: 'Fixas: 10-15 anos. Remov\u00edveis: reembasamento a cada 5-7 anos.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'A pr\u00f3tese certa,', bronzeItalic: 'para o seu caso.', description: 'Cada caso tem alternativas. A primeira consulta apresenta as suas, com pr\u00f3s e contras, prazos e valores.' },
  },

  'profilaxia': {
    metadata: { title: 'Profilaxia | Biodonth', description: 'Profilaxia dental em Arthur Alvim \u2014 limpeza profissional profunda. A visita preventiva mais importante do ano.' },
    hero: { eyebrow: 'Tratamento \u2022 Profilaxia', bronze: 'A limpeza', bronzeItalic: 'que escova nenhuma alcan\u00e7a.', description: 'A \u00fanica consulta que pedimos para n\u00e3o pular nunca \u2014 porque evita 80% dos problemas que outros tratamentos teriam que resolver.' },
    consider: { eyebrow: 'Quando agendar', title: 'Pelo menos', titleItalic: 'uma vez por ano.', intro: 'A recomenda\u00e7\u00e3o universal \u00e9 a cada 6 meses. Vale agendar quando:', signals: ['\u00daltima limpeza h\u00e1 mais de 1 ano.', 'Sangramento na escova\u00e7\u00e3o ou fio dental.', 'Gengiva inchada, vermelha ou retra\u00edda.', 'Mau h\u00e1lito recorrente.', 'Ac\u00famulo amarelado na linha da gengiva.', 'Vai come\u00e7ar outro tratamento odontol\u00f3gico.'], bridge: 'Profilaxia regular \u00e9 a melhor forma de manter a boca saud\u00e1vel e evitar tratamentos mais caros.' },
    approach: { eyebrow: 'Como tratamos', title: 'Limpeza profunda,', titleItalic: 'feita com tempo.', intro: 'N\u00e3o \u00e9 raspagem r\u00e1pida de 15 minutos. \u00c9 sess\u00e3o completa de 45 a 90 minutos.', steps: [{ number: '01', title: 'Avalia\u00e7\u00e3o pr\u00e9via.', body: 'Estado da gengiva e identifica\u00e7\u00e3o de \u00e1reas com mais ac\u00famulo.' }, { number: '02', title: 'Remo\u00e7\u00e3o de t\u00e1rtaro.', body: 'Instrumentos manuais e ultras\u00f4nicos. Limpeza completa em toda a arcada.' }, { number: '03', title: 'Polimento.', body: 'Remo\u00e7\u00e3o de manchas extr\u00ednsecas e devolu\u00e7\u00e3o do brilho natural.' }, { number: '04', title: 'Fl\u00faor (quando indicado).', body: 'Refor\u00e7a o esmalte e reduz risco de c\u00e1rie nos meses seguintes.' }, { number: '05', title: 'Orienta\u00e7\u00e3o personalizada.', body: 'T\u00e9cnica de escova\u00e7\u00e3o, escolha de escova e fio dental para o seu caso.' }] },
    results: { eyebrow: 'O que esperar', title: 'Efeito imediato', titleItalic: 'e de longo prazo.', paragraphs: ['Imediato: dentes lisos, h\u00e1lito limpo, "boca renovada".', 'Longo prazo: menos c\u00e1ries, menos doen\u00e7a periodontal, menos urg\u00eancias.'], moments: [{ title: 'A l\u00edngua que percorre.', body: 'Tudo liso, livre, como rec\u00e9m-sa\u00eddos da gengiva.' }, { title: 'O brilho no espelho.', body: 'Dentes parecem mais claros, sem ter mudado a cor.' }, { title: 'O fio que desliza.', body: 'Sem topar com nada. Boca em ordem.' }] },
    investment: { eyebrow: 'Investimento', title: 'Simples', titleItalic: 'e essencial.', paragraphs: ['Valor fixo e previs\u00edvel. Cabe no or\u00e7amento da maioria das fam\u00edlias.', 'Cada R$ em preven\u00e7\u00e3o evita R$ 4-5 em tratamentos curativos.'], factors: ['Ac\u00famulo de t\u00e1rtaro.', 'Estado da gengiva.', 'Necessidade de fl\u00faor.', 'Casos com periodontite exigem raspagem mais profunda.'], closing: 'A consulta que mais economiza no longo prazo.' },
    faq: [{ question: 'D\u00f3i?', answer: 'Em condi\u00e7\u00f5es normais, n\u00e3o. Pacientes com gengiva muito sens\u00edvel podem usar gel anest\u00e9sico.' }, { question: 'Clareia os dentes?', answer: 'Indiretamente. A remo\u00e7\u00e3o de manchas devolve a cor natural, que costuma ser mais clara do que aparenta.' }, { question: 'Com que frequ\u00eancia?', answer: 'A cada 6 meses. Casos de alto risco: a cada 3-4 meses.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'A primeira limpeza', bronzeItalic: 'do ano.', description: 'Sem grande compromisso, sem investimento alto. Apenas a base que mant\u00e9m todo o resto funcionando.' },
  },

  'saude-gengiva': {
    metadata: { title: 'Sa\u00fade da gengiva | Biodonth', description: 'Tratamento periodontal em Arthur Alvim \u2014 diagn\u00f3stico e tratamento de gengivite e periodontite.' },
    hero: { eyebrow: 'Tratamento \u2022 Sa\u00fade da gengiva', bronze: 'A gengiva \u00e9', bronzeItalic: 'o alicerce.', description: 'Antes de qualquer est\u00e9tica, antes de qualquer implante \u2014 a gengiva. Quando ela cai, o resto vem junto.' },
    consider: { eyebrow: 'Quando vale considerar', title: 'Sinais de que', titleItalic: 'a gengiva pede aten\u00e7\u00e3o.', intro: 'Doen\u00e7a periodontal \u00e9 a principal causa de perda de dentes em adultos. Avan\u00e7a silenciosa:', signals: ['Gengiva que sangra na escova\u00e7\u00e3o ou fio dental.', 'Gengiva vermelha, inchada ou sens\u00edvel.', 'Mau h\u00e1lito recorrente.', 'Dentes que parecem "maiores" \u2014 gengiva retraindo.', 'Mobilidade em algum dente.', 'Ac\u00famulo f\u00e1cil de t\u00e1rtaro.', 'Hist\u00f3rico familiar de doen\u00e7a periodontal.', 'Fumante, diab\u00e9tico ou sob estresse cr\u00f4nico.'], bridge: 'Gengivite \u00e9 revers\u00edvel. Periodontite diagnosticada cedo \u00e9 control\u00e1vel. O fator decisivo \u00e9 o tempo at\u00e9 o diagn\u00f3stico.' },
    approach: { eyebrow: 'Como tratamos', title: 'Periodontia', titleItalic: 'feita com crit\u00e9rio.', intro: 'O tratamento se adapta ao est\u00e1gio da doen\u00e7a. Abordagem cuidadosa com medi\u00e7\u00f5es precisas.', steps: [{ number: '01', title: 'Avalia\u00e7\u00e3o periodontal.', body: 'Sondagem em 6 pontos por dente. Registro de sangramento, mobilidade e perda \u00f3ssea.' }, { number: '02', title: 'Diagn\u00f3stico e classifica\u00e7\u00e3o.', body: 'Sa\u00fade periodontal, gengivite ou periodontite (est\u00e1gios I-IV). Cada um com tratamento pr\u00f3prio.' }, { number: '03', title: 'Raspagem e alisamento.', body: 'Remo\u00e7\u00e3o de t\u00e1rtaro subgengival com curetas e ultrassom. 1-4 sess\u00f5es.' }, { number: '04', title: 'Reavalia\u00e7\u00e3o.', body: 'Nova sondagem em 4-6 semanas. Mais de 80% dos casos respondem bem sem cirurgia.' }, { number: '05', title: 'Cirurgia (quando necess\u00e1ria).', body: 'Acesso, enxertos gengivais ou regenera\u00e7\u00e3o tecidual guiada para casos avan\u00e7ados.' }, { number: '06', title: 'Manuten\u00e7\u00e3o \u2014 permanente.', body: 'Consultas a cada 3-4 meses com sondagem peri\u00f3dica. Periodontite \u00e9 controlada, n\u00e3o curada.' }] },
    results: { eyebrow: 'O que esperar', title: 'A gengiva que', titleItalic: 'volta a ser invis\u00edvel.', paragraphs: ['Gengiva saud\u00e1vel \u00e9 gengiva que voc\u00ea n\u00e3o percebe. N\u00e3o sangra, n\u00e3o d\u00f3i, n\u00e3o chama aten\u00e7\u00e3o.', 'A longo prazo: preserva\u00e7\u00e3o dos dentes. Pacientes com periodontite controlada mant\u00eam os pr\u00f3prios dentes.'], moments: [{ title: 'Fio sem sangue.', body: 'Voc\u00ea passa o fio, retira branco. Sem o lembrete da inflama\u00e7\u00e3o.' }, { title: 'H\u00e1lito que n\u00e3o te lembra.', body: 'Falar perto de algu\u00e9m sem c\u00e1lculo autom\u00e1tico sobre o cheiro.' }, { title: 'O dente que parou de pedir.', body: 'Voltou ao normal. Parou de chamar aten\u00e7\u00e3o.' }] },
    investment: { eyebrow: 'Investimento', title: 'Adaptado', titleItalic: 'ao est\u00e1gio.', paragraphs: ['Gengivite: 1-2 sess\u00f5es. Periodontite avan\u00e7ada: 4-6 sess\u00f5es + poss\u00edvel cirurgia.', 'Diagn\u00f3stico precoce = tratamento simples = custo menor.'], factors: ['Est\u00e1gio da doen\u00e7a.', 'N\u00famero de \u00e1reas afetadas.', 'Necessidade de cirurgia.', 'Fatores de risco (fumo, diabetes).', 'Frequ\u00eancia da manuten\u00e7\u00e3o.'], closing: 'A primeira consulta inclui sondagem completa, diagn\u00f3stico e plano com prazos e valores.' },
    faq: [{ question: 'Periodontite tem cura?', answer: 'N\u00e3o no sentido estrito. Mas com tratamento adequado e manuten\u00e7\u00e3o, fica controlada. Em 80%+ dos casos, para sempre.' }, { question: 'Sangra ao passar fio. \u00c9 grave?', answer: 'Sinal de gengivite \u2014 revers\u00edvel em 1-2 semanas com limpeza profissional. Mas ignorada vira periodontite.' }, { question: 'Sou fumante. Adianta tratar?', answer: 'Adianta, mas resposta ao tratamento \u00e9 pior enquanto fuma. Conversamos com honestidade sobre isso.' }],
    closing: { eyebrow: 'Pr\u00f3ximos passos', bronze: 'O alicerce', bronzeItalic: 'come\u00e7a na sondagem.', description: 'Antes de qualquer est\u00e9tica ou reabilita\u00e7\u00e3o, vale avaliar a gengiva. A primeira consulta inclui sondagem completa.' },
  },
};
